version: '3.9'

services:
  backend:
    image: backend
    build:
      context: ./backend/client-management-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/client-management-api:/app-backend
    environment:
      - DB_HOSTNAME=tryber-trybe-track-db.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=L7Y61neO0tsj87h
      - DB_NAME=tryber_trybe_track

  frontend:
    image: frontend
    build:
      context: ./frontend/client-management
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/client-management:/app-frontend

