services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app-backend
    environment:
      - DB_HOSTNAME=tryber-trybe-track-db.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=L7Y61neO0tsj87h
      - DB_NAME=tryber_trybe_track

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app-frontend
      - /app-frontend/node_modules

